### ISSUE TITLE
Train a neural network to play QPong

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-hackathon-singapore-19#10]
# Abstract
![QPong-1](https://user-images.githubusercontent.com/7631333/66051005-c2d6f800-e560-11e9-8066-ae0640592199.gif)

Train a neural network to play [QPong](https://github.com/HuangJunye/QPong), using genetic algorithm, similar to this project: https://github.com/greerviau/SnakeAI

# Description 
QPong is a quantum version of Pong made by @HuangJunye 's team in Qiskit Camp 2019. The idea of this project is to train a neural network to play QPong. Here are some ideas:

1. Train a neural network to play classical Pong against normal computer player.
2. Train a neural network to play quantum Pong against normal computer player.
3. Let the classical Pong AI compete with quantum Pong AI 

Hopefully there will be some insights to be gained from QPong AI. Even if there will no none, it will be certainly fun to watch the AI playing QPong. :)

# Members

 - Andrew Tan
 - Kyle Chu
 - Lee Jun Yao Francis
 - Brandon Hsu
 - Qiskit Coach: @HuangJunye, Slack: `@Junye`

# Deliverable

- A trained neural network for playing CPong and QPong
- (Optional) a cool Youtube video of the evolution of training similar to this: https://www.youtube.com/watch?v=zIkBYwdkuTk&t

# GitHub repo

**Comment by fustilio** [comment]
Let's do this

**Comment by ktnc985** [comment]
I'm in

**Comment by hannahrawr** [comment]
I'm in!

**Comment by brandhsu** [comment]
^
