### ISSUE TITLE
Fault-tolerant synthesis of Z rotations

### ISSUE THREAD

**Issue by ajavadia** [qiskit-community/qiskit-hackathon-singapore-19#19]
# Abstract
Refer to https://github.com/Qiskit/qiskit-terra/issues/3212

# Description 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by HuangJunye** [comment]
Thanks @ajavadia for adding the idea!
