### ISSUE TITLE
Brain Computer Interface + Qiskit

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-hackathon-singapore-19#24]
# Abstract

Use OpenBCI to work with Qiskit. Make a boxing game or something else. More details will be added.
# Description 

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @githubhandle 

# Deliverable

# GitHub repo

**Comment by HuangJunye** [comment]
Philippe will add the details later. He wants to look for people with machine learning background.

**Comment by HuangJunye** [comment]
So we're going for boxing game, we have a working BCI and we though it will be fun to have actions triggered by brainwaves. We pretty much need someone who can code a simple classifier.

**Comment by salamatburj** [comment]
Hey! Is there any quantum computation involved in the project?
