### ISSUE TITLE
Quantum Shooter with Qiskit

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-hackathon-singapore-19#8]
# Abstract
![QuantumShooter](https://user-images.githubusercontent.com/7631333/66049190-8655cd00-e55d-11e9-94b9-3d499e29071a.gif)
Make a quantum game with Qiskit and [PICO-8](https://www.lexaloffle.com/pico-8.php) based on the [Quantum Shooter](https://kirais.itch.io/quantum-shooter) game I made in a game jam in September.
# Description 
Quantum shooter is polarity shoot 'em up game inspired by [Ikaruga](https://en.wikipedia.org/wiki/Ikaruga). Your ship and its bullets have two different polarities: blue and red, so as your enemies. When your bullet has different color from the enemies', it deals bonus damage (2x). And your ship is immune to enemies' bullet of the same color. 

The idea of the project is to fill the existing game with quantum physics and Qiskit! Here are some ideas:
1. The two polarities can be treated as eigenstates in two different bases, for example, Z basis (|0>/|1>) or X basis (|+>/|->).
2. The bullets can be quantum gates (X gate or H gate). X gate can only attack enemies with Z basis state and H gate can only attack enemies with X basis states.

# Members

 - @githubhandle
 - @githubhandle
 - Qiskit Coach: @HuangJunye Slack: `@Junye`

# Deliverable

A playable PICO-8 game that works with Qiskit

# GitHub repo

https://github.com/HuangJunye/Quantum-Shooter

**Comment by 1ucian0** [comment]
@HuangJunye thinks this project might be too hard difficult, hence the closing.
