### ISSUE TITLE
Quantum Sokoban/Pushblock puzzle game

### ISSUE THREAD

**Issue by HuangJunye** [qiskit-community/qiskit-hackathon-singapore-19#9]
# Abstract
![Quantum Gate Puzzle](https://user-images.githubusercontent.com/7631333/66050043-0a5c8480-e55f-11e9-8013-27883f27199e.gif)

Make a quantum version of [Sokoban](https://en.wikipedia.org/wiki/Sokoban) or Pushblock puzzle game. Some ideas are implemented in a game jam game that I made in August: [The Adventure of Rick](https://kirais.itch.io/the-adventure-of-rick-grad-school)

# Description 

# Members

 - @Lidia-LP 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @HuangJunye, Slack: `@Junye`

# Deliverable

A playable game developed in any game engine that uses Qiskit.

# GitHub repo

**Comment by Lidia-LP** [comment]
I would be interested in this!

**Comment by kelvinloh89** [comment]
I am interested in this
